export const actionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    DELETE_PRODUCT : "DELETE_PRODUCT",

    SET_AUTHORITIES : "SET_AUTHORITIES",
    SELECTED_AUTHORITIE : "SELECTED_AUTHORITIE",
    REMOVE_AUTHORITIE : "REMOVE_AUTHORITIE",
    ADD_AUTHORITIE : "ADD_AUTHORITIE", 
    UPDATE_AUTHORITIE : "UPDATE_AUTHORITIE",
    REMOVE_SELECTED_AUTHORITIE: "REMOVE_SELECTED_AUTHORITIE",
    RESET_AUTHORITIES : "RESET_AUTHORITIES",

    SET_BRANCHS : "SET_BRANCHS",
    SELECTED_BRANCH : "SELECTED_BRANCH",
    REMOVE_BRANCH : "REMOVE_BRANCH",
    ADD_BRANCH : "ADD_BRANCH",
    BRANCH_UPDATED: "BRANCH_UPDATED",
    RESET_BRANCH : "RESET_BRANCH",

    SET_ANNOUNCES : "SET_ANNOUNCES",
    SELECTED_ANNOUNCE : "SELECTED_ANNOUNCE",
    SELECTED_ANNOUNCE_AUTHORITIE : "SELECTED_ANNOUNCE_AUTHORITIE",
    REMOVE_ANNOUNCE : "REMOVE_ANNOUNCE",
    ADD_ANNOUNCE : "ADD_ANNOUNCE",
    UPDATE_ANNOUNCE : "UPDATE_ANNOUNCE",
    REMOVE_SELECTED_ANNOUNCE : "REMOVE_SELECTED_ANNOUNCE",
    LOAD_ANNOUNCE_DATA : "LOAD_ANNOUNCE_DATA",

    SET_INCIDENTS : "SET_INCIDENTS",
    SELECTED_INCIDENT : "SELECTED_INCIDENT",
    REMOVE_INCIDENT : "REMOVE_INCIDENT",
    ADD_INCIDENT : "ADD_INCIDENT",
    UPDATE_INCIDENT : "UPDATE_INCIDENT",
    REMOVE_SELECTED_INCIDENT : "REMOVE_SELECTED_INCIDENT",

    SET_REPORTS : "SET_REPORTS",
    SET_REPORTS_INCIDENTS : "SET_REPORTS_INCIDENTS",
    SET_REPORTS_NEARBY : "SET_REPORTS_NEARBY",
    SET_REPORTS_AUTHORITIE : "SET_REPORTS_AUTHORITIE",
    SELECTED_REPORT : "SELECTED_REPORT",
    REMOVE_REPORT : "REMOVE_REPORT",
    ADD_REPORT : "ADD_REPORT",
    UPDATE_REPORT : "UPDATE_REPORT",

    SET_WILAYAS : "SET_WILAYAS",
    SELECTED_WILAYA : "SELECTED_WILAYA",
    SET_DAIRAS : "SET_DAIRAS",
    SELECTED_DAIRA : "SELECTED_DAIRA",
    SET_COMMUNES : "SET_COMMUNES",
    SELECTED_COMMUNE : "SELECTED_COMMUNE",

    USER_LOGIN : "USER_LOGIN",
    USER_LOGOUT : "USER_LOGOUT",
    USER_INFO : "USER_INFO",


    ADD_USER : "ADD_USER",
    UPDATE_USER : "UPDATE_USER",
    DELETE_USER : "DELETE_USER",


    AUTHORITIE_USERS_LOADED : "AUTHORITIE_USERS_LOADED",
    WILAYA_USERS_LOADED : "WILAYA_USERS_LOADED",


}