<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Daira;

class DairaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Dairaitems = [
            [ 'id' => '101', 'name' => 'Adrar', 'ar_name' => 'أدرار', 'slug' => 'adrar', 'wilaya_id' => 1 ],
            [ 'id' => '104', 'name' => 'Reggane', 'ar_name' => 'رقان', 'slug' => 'reggane', 'wilaya_id' => 1 ],
            [ 'id' => '108', 'name' => 'Tsabit', 'ar_name' => 'تسابيت', 'slug' => 'tsabit', 'wilaya_id' => 1 ],
            [ 'id' => '111', 'name' => 'Zaouiat Kounta', 'ar_name' => 'زاوية كنتة', 'slug' => 'zaouiat-kounta', 'wilaya_id' => 1 ],
            [ 'id' => '112', 'name' => 'Aoulef', 'ar_name' => 'أولف', 'slug' => 'aoulef', 'wilaya_id' => 1 ],
            [ 'id' => '115', 'name' => 'Fenoughil', 'ar_name' => 'فنوغيل', 'slug' => 'fenoughil', 'wilaya_id' => 1 ],
            [ 'id' => '201', 'name' => 'Chlef', 'ar_name' => 'الشلف', 'slug' => 'chlef', 'wilaya_id' => 2 ],
            [ 'id' => '202', 'name' => 'Tenes', 'ar_name' => 'تنس', 'slug' => 'tenes', 'wilaya_id' => 2 ],
            [ 'id' => '204', 'name' => 'El Karimia', 'ar_name' => 'الكريمية', 'slug' => 'el-karimia', 'wilaya_id' => 2 ],
            [ 'id' => '206', 'name' => 'Taougrit', 'ar_name' => 'تاوقريت', 'slug' => 'taougrit', 'wilaya_id' => 2 ],
            [ 'id' => '207', 'name' => 'Beni Haoua', 'ar_name' => 'بني حواء', 'slug' => 'beni-haoua', 'wilaya_id' => 2 ],
            [ 'id' => '210', 'name' => 'Ouled Fares', 'ar_name' => 'أولاد فارس', 'slug' => 'ouled-fares', 'wilaya_id' => 2 ],
            [ 'id' => '212', 'name' => 'Boukadir', 'ar_name' => 'بوقادير', 'slug' => 'boukadir', 'wilaya_id' => 2 ],
            [ 'id' => '220', 'name' => 'Zeboudja', 'ar_name' => 'الزبوجة', 'slug' => 'zeboudja', 'wilaya_id' => 2 ],
            [ 'id' => '222', 'name' => 'Abou El Hassane', 'ar_name' => 'أبو الحسن', 'slug' => 'abou-el-hassane', 'wilaya_id' => 2 ],
            [ 'id' => '223', 'name' => 'El Marsa', 'ar_name' => 'المرسى', 'slug' => 'el-marsa', 'wilaya_id' => 2 ],
            [ 'id' => '229', 'name' => 'Oued Fodda', 'ar_name' => 'وادي الفضة', 'slug' => 'oued-fodda', 'wilaya_id' => 2 ],
            [ 'id' => '230', 'name' => 'Ouled Ben Abdelkader', 'ar_name' => 'أولاد بن عبد القادر', 'slug' => 'ouled-ben-abdelkader', 'wilaya_id' => 2 ],
            [ 'id' => '232', 'name' => 'Ain Merane', 'ar_name' => 'عين مران', 'slug' => 'ain-merane', 'wilaya_id' => 2 ],
            [ 'id' => '301', 'name' => 'Laghouat', 'ar_name' => 'الأغواط', 'slug' => 'laghouat', 'wilaya_id' => 3 ],
            [ 'id' => '302', 'name' => 'Ksar El Hirane', 'ar_name' => 'قصر الحيران', 'slug' => 'ksar-el-hirane', 'wilaya_id' => 3 ],
            [ 'id' => '304', 'name' => 'Sidi Makhlouf', 'ar_name' => 'سيدي مخلوف', 'slug' => 'sidi-makhlouf', 'wilaya_id' => 3 ],
            [ 'id' => '306', 'name' => "Hassi R'mel", 'ar_name' => 'حاسي الرمل', 'slug' => 'hassi-rmel', 'wilaya_id' => 3 ],
            [ 'id' => '307', 'name' => 'Ain Madhi', 'ar_name' => 'عين ماضي', 'slug' => 'ain-madhi', 'wilaya_id' => 3 ],
            [ 'id' => '310', 'name' => 'Gueltat Sidi Saad', 'ar_name' => 'قتلة سيدي سعيد', 'slug' => 'gueltat-sidi-saad', 'wilaya_id' => 3 ],
            [ 'id' => '313', 'name' => 'Brida', 'ar_name' => 'بريدة', 'slug' => 'brida', 'wilaya_id' => 3 ],
            [ 'id' => '314', 'name' => 'El Ghicha', 'ar_name' => 'الغيشة', 'slug' => 'el-ghicha', 'wilaya_id' => 3 ],
            [ 'id' => '319', 'name' => 'Aflou', 'ar_name' => 'أفلو', 'slug' => 'aflou', 'wilaya_id' => 3 ],
            [ 'id' => '321', 'name' => 'Oued Morra', 'ar_name' => 'وادي مرة', 'slug' => 'oued-morra', 'wilaya_id' => 3 ],
            [ 'id' => '401', 'name' => 'Oum El Bouaghi', 'ar_name' => 'أم البواقي', 'slug' => 'oum-el-bouaghi', 'wilaya_id' => 4 ],
            [ 'id' => '402', 'name' => 'Ain Beida', 'ar_name' => 'عين البيضاء', 'slug' => 'ain-beida', 'wilaya_id' => 4 ],
            [ 'id' => '403', 'name' => "Ain M'lila", 'ar_name' => 'عين مليلة', 'slug' => 'ain-mlila', 'wilaya_id' => 4 ],
            [ 'id' => '406', 'name' => 'Sigus', 'ar_name' => 'سيقوس', 'slug' => 'sigus', 'wilaya_id' => 4 ],
            [ 'id' => '408', 'name' => 'Ain Babouche', 'ar_name' => 'عين ببوش', 'slug' => 'ain-babouche', 'wilaya_id' => 4 ],
            [ 'id' => '411', 'name' => 'Dhalaa', 'ar_name' => 'الضلعة', 'slug' => 'dhalaa', 'wilaya_id' => 4 ],
            [ 'id' => '412', 'name' => 'Ain Kercha', 'ar_name' => 'عين كرشة', 'slug' => 'ain-kercha', 'wilaya_id' => 4 ],
            [ 'id' => '416', 'name' => "F'kirina", 'ar_name' => 'فكيرينة', 'slug' => 'fkirina', 'wilaya_id' => 4 ],
            [ 'id' => '417', 'name' => 'Souk Naamane', 'ar_name' => 'سوق نعمان', 'slug' => 'souk-naamane', 'wilaya_id' => 4 ],
            [ 'id' => '422', 'name' => 'Ksar Sbahi', 'ar_name' => 'قصر الصباحي', 'slug' => 'ksar-sbahi', 'wilaya_id' => 4 ],
            [ 'id' => '424', 'name' => 'Meskiana', 'ar_name' => 'مسكيانة', 'slug' => 'meskiana', 'wilaya_id' => 4 ],
            [ 'id' => '425', 'name' => 'Ain Fekroun', 'ar_name' => 'عين فكرون', 'slug' => 'ain-fekroun', 'wilaya_id' => 4 ],
            [ 'id' => '501', 'name' => 'Batna', 'ar_name' => 'باتنة', 'slug' => 'batna', 'wilaya_id' => 5 ],
            [ 'id' => '504', 'name' => 'Merouana', 'ar_name' => 'مروانة', 'slug' => 'merouana', 'wilaya_id' => 5 ],
            [ 'id' => '505', 'name' => 'Seriana', 'ar_name' => 'سريانة', 'slug' => 'seriana', 'wilaya_id' => 5 ],
            [ 'id' => '506', 'name' => 'Menaa', 'ar_name' => 'منعة', 'slug' => 'menaa', 'wilaya_id' => 5 ],
            [ 'id' => '507', 'name' => 'El Madher', 'ar_name' => 'المعذر', 'slug' => 'el-madher', 'wilaya_id' => 5 ],
            [ 'id' => '508', 'name' => 'Tazoult', 'ar_name' => 'تازولت', 'slug' => 'tazoult', 'wilaya_id' => 5 ],
            [ 'id' => '509', 'name' => "N'gaous", 'ar_name' => 'نقاوس', 'slug' => 'ngaous', 'wilaya_id' => 5 ],
            [ 'id' => '516', 'name' => 'Arris', 'ar_name' => 'أريس', 'slug' => 'arris', 'wilaya_id' => 5 ],
            [ 'id' => '519', 'name' => 'Ain Djasser', 'ar_name' => 'عين جاسر', 'slug' => 'ain-djasser', 'wilaya_id' => 5 ],
            [ 'id' => '529', 'name' => 'Seggana', 'ar_name' => 'سقانة', 'slug' => 'seggana', 'wilaya_id' => 5 ],
            [ 'id' => '530', 'name' => 'Ichemoul', 'ar_name' => 'إشمول', 'slug' => 'ichemoul', 'wilaya_id' => 5 ],
            [ 'id' => '535', 'name' => 'Bouzina', 'ar_name' => 'بوزينة', 'slug' => 'bouzina', 'wilaya_id' => 5 ],
            [ 'id' => '536', 'name' => 'Chemora', 'ar_name' => 'الشمرة', 'slug' => 'chemora', 'wilaya_id' => 5 ],
            [ 'id' => '542', 'name' => 'Barika', 'ar_name' => 'بريكة', 'slug' => 'barika', 'wilaya_id' => 5 ],
            [ 'id' => '543', 'name' => 'Djezzar', 'ar_name' => 'الجزار', 'slug' => 'djezzar', 'wilaya_id' => 5 ],
            [ 'id' => '544', 'name' => 'Tkout', 'ar_name' => 'تكوت', 'slug' => 'tkout', 'wilaya_id' => 5 ],
            [ 'id' => '545', 'name' => 'Ain Touta', 'ar_name' => 'عين التوتة', 'slug' => 'ain-touta', 'wilaya_id' => 5 ],
            [ 'id' => '547', 'name' => 'Theniet El Abed', 'ar_name' => 'ثنية العابد', 'slug' => 'theniet-el-abed', 'wilaya_id' => 5 ],
            [ 'id' => '550', 'name' => 'Timgad', 'ar_name' => 'تيمقاد', 'slug' => 'timgad', 'wilaya_id' => 5 ],
            [ 'id' => '551', 'name' => 'Ras El Aioun', 'ar_name' => 'رأس العيون', 'slug' => 'ras-el-aioun', 'wilaya_id' => 5 ],
            [ 'id' => '553', 'name' => 'Ouled Si Slimane', 'ar_name' => 'أولاد سي سليمان', 'slug' => 'ouled-si-slimane', 'wilaya_id' => 5 ],
            [ 'id' => '601', 'name' => 'Bejaia', 'ar_name' => 'بجاية', 'slug' => 'bejaia', 'wilaya_id' => 6 ],
            [ 'id' => '602', 'name' => 'Amizour', 'ar_name' => 'أميزور', 'slug' => 'amizour', 'wilaya_id' => 6 ],
            [ 'id' => '607', 'name' => 'Timezrit', 'ar_name' => 'تيمزريت', 'slug' => 'timezrit', 'wilaya_id' => 6 ],
            [ 'id' => '608', 'name' => 'Souk El Tenine', 'ar_name' => 'سوق الإثنين', 'slug' => 'souk-el-tenine', 'wilaya_id' => 6 ],
            [ 'id' => '611', 'name' => 'Tichy', 'ar_name' => 'تيشي', 'slug' => 'tichy', 'wilaya_id' => 6 ],
            [ 'id' => '617', 'name' => 'Ighil Ali', 'ar_name' => 'إغيل علي', 'slug' => 'ighil-ali', 'wilaya_id' => 6 ],
            [ 'id' => '620', 'name' => 'Darguina', 'ar_name' => 'درقينة', 'slug' => 'darguina', 'wilaya_id' => 6 ],
            [ 'id' => '622', 'name' => 'Aokas', 'ar_name' => 'أوقاس', 'slug' => 'aokas', 'wilaya_id' => 6 ],
            [ 'id' => '624', 'name' => 'Adekar', 'ar_name' => 'أدكار', 'slug' => 'adekar', 'wilaya_id' => 6 ],
            [ 'id' => '625', 'name' => 'Akbou', 'ar_name' => 'أقبو', 'slug' => 'akbou', 'wilaya_id' => 6 ],
            [ 'id' => '626', 'name' => 'Seddouk', 'ar_name' => 'صدوق', 'slug' => 'seddouk', 'wilaya_id' => 6 ],
            [ 'id' => '627', 'name' => 'Tazmalt', 'ar_name' => 'تازملت', 'slug' => 'tazmalt', 'wilaya_id' => 6 ],
            [ 'id' => '629', 'name' => 'Chemini', 'ar_name' => 'شميني', 'slug' => 'chemini', 'wilaya_id' => 6 ],
            [ 'id' => '634', 'name' => 'Barbacha', 'ar_name' => 'برباشة', 'slug' => 'barbacha', 'wilaya_id' => 6 ],
            [ 'id' => '636', 'name' => 'Ifri Ouzellaguene', 'ar_name' => 'إفري أوزلاقن', 'slug' => 'ifri-ouzellaguene', 'wilaya_id' => 6 ],
            [ 'id' => '639', 'name' => 'Sidi Aich', 'ar_name' => 'سيدي عيش', 'slug' => 'sidi-aich', 'wilaya_id' => 6 ],
            [ 'id' => '640', 'name' => 'El Kseur', 'ar_name' => 'القصر', 'slug' => 'el-kseur', 'wilaya_id' => 6 ],
            [ 'id' => '644', 'name' => 'Kherrata', 'ar_name' => 'خراطة', 'slug' => 'kherrata', 'wilaya_id' => 6 ],
            [ 'id' => '650', 'name' => 'Beni Maouche', 'ar_name' => 'بني معوش', 'slug' => 'beni-maouche', 'wilaya_id' => 6 ],
            [ 'id' => '701', 'name' => 'Biskra', 'ar_name' => 'بسكرة', 'slug' => 'biskra', 'wilaya_id' => 7 ],
            [ 'id' => '711', 'name' => 'Sidi Okba', 'ar_name' => 'سيدي عقبة', 'slug' => 'sidi-okba', 'wilaya_id' => 7 ],
            [ 'id' => '712', 'name' => 'Mechouneche', 'ar_name' => 'مشونش', 'slug' => 'mechouneche', 'wilaya_id' => 7 ],
            [ 'id' => '715', 'name' => 'Zeribet El Oued', 'ar_name' => 'زريبة الوادي', 'slug' => 'zeribet-el-oued', 'wilaya_id' => 7 ],
            [ 'id' => '717', 'name' => 'El Kantara', 'ar_name' => 'القنطرة', 'slug' => 'el-kantara', 'wilaya_id' => 7 ],
            [ 'id' => '719', 'name' => 'El Outaya', 'ar_name' => 'الوطاية', 'slug' => 'el-outaya', 'wilaya_id' => 7 ],
            [ 'id' => '720', 'name' => 'Djemorah', 'ar_name' => 'جمورة', 'slug' => 'djemorah', 'wilaya_id' => 7 ],
            [ 'id' => '721', 'name' => 'Tolga', 'ar_name' => 'طولقة', 'slug' => 'tolga', 'wilaya_id' => 7 ],
            [ 'id' => '724', 'name' => 'Ourlal', 'ar_name' => 'أورلال', 'slug' => 'ourlal', 'wilaya_id' => 7 ],
            [ 'id' => '726', 'name' => 'Foughala', 'ar_name' => 'فوغالة', 'slug' => 'foughala', 'wilaya_id' => 7 ],
            [ 'id' => '801', 'name' => 'Bechar', 'ar_name' => 'بشار', 'slug' => 'bechar', 'wilaya_id' => 8 ],
            [ 'id' => '806', 'name' => 'Lahmar', 'ar_name' => 'لحمر', 'slug' => 'lahmar', 'wilaya_id' => 8 ],
            [ 'id' => '810', 'name' => 'Kenadsa', 'ar_name' => 'القنادسة', 'slug' => 'kenadsa', 'wilaya_id' => 8 ],
            [ 'id' => '812', 'name' => 'Tabelbala', 'ar_name' => 'تبلبالة', 'slug' => 'tabelbala', 'wilaya_id' => 8 ],
            [ 'id' => '813', 'name' => 'Taghit', 'ar_name' => 'تاغيت', 'slug' => 'taghit', 'wilaya_id' => 8 ],
            [ 'id' => '817', 'name' => 'Abadla', 'ar_name' => 'العبادلة', 'slug' => 'abadla', 'wilaya_id' => 8 ],
            [ 'id' => '821', 'name' => 'Beni Ounif', 'ar_name' => 'بني ونيف', 'slug' => 'beni-ounif', 'wilaya_id' => 8 ],
            [ 'id' => '901', 'name' => 'Blida', 'ar_name' => 'البليدة', 'slug' => 'blida', 'wilaya_id' => 9 ],
            [ 'id' => '903', 'name' => 'Bouinan', 'ar_name' => 'بوعينان', 'slug' => 'bouinan', 'wilaya_id' => 9 ],
            [ 'id' => '904', 'name' => 'Oued El Alleug', 'ar_name' => 'وادي العلايق', 'slug' => 'oued-el-alleug', 'wilaya_id' => 9 ],
            [ 'id' => '905', 'name' => 'Ouled Yaich', 'ar_name' => 'أولاد يعيش', 'slug' => 'ouled-yaich', 'wilaya_id' => 9 ],
            [ 'id' => '907', 'name' => 'El Affroun', 'ar_name' => 'العفرون', 'slug' => 'el-affroun', 'wilaya_id' => 9 ],
            [ 'id' => '912', 'name' => 'Mouzaia', 'ar_name' => 'موزاية', 'slug' => 'mouzaia', 'wilaya_id' => 9 ],
            [ 'id' => '914', 'name' => 'Meftah', 'ar_name' => 'مفتاح', 'slug' => 'meftah', 'wilaya_id' => 9 ],
            [ 'id' => '916', 'name' => 'Boufarik', 'ar_name' => 'بوفاريك', 'slug' => 'boufarik', 'wilaya_id' => 9 ],
            [ 'id' => '917', 'name' => 'Larbaa', 'ar_name' => 'الأربعاء', 'slug' => 'larbaa', 'wilaya_id' => 9 ],
            [ 'id' => '922', 'name' => 'Bougara', 'ar_name' => 'بوقرة', 'slug' => 'bougara', 'wilaya_id' => 9 ],
            [ 'id' => '1001', 'name' => 'Bouira', 'ar_name' => 'البويرة', 'slug' => 'bouira', 'wilaya_id' => 10 ],
            [ 'id' => '1004', 'name' => 'Souk El Khemis', 'ar_name' => 'سوق الخميس', 'slug' => 'souk-el-khemis', 'wilaya_id' => 10 ],
            [ 'id' => '1005', 'name' => 'Kadiria', 'ar_name' => 'القادرية', 'slug' => 'kadiria', 'wilaya_id' => 10 ],
            [ 'id' => '1012', 'name' => 'Haizer', 'ar_name' => 'الحيزر', 'slug' => 'haize', 'wilaya_id' => 10 ],
            [ 'id' => '1013', 'name' => 'Lakhdaria', 'ar_name' => 'الأخضرية', 'slug' => 'lakhdaria', 'wilaya_id' => 10 ],
            [ 'id' => '1015', 'name' => 'El Hachimia', 'ar_name' => 'الهاشمية', 'slug' => 'el-hachimia', 'wilaya_id' => 10 ],
            [ 'id' => '1018', 'name' => 'Bordj Okhriss', 'ar_name' => 'برج أوخريص', 'slug' => 'bordj-okhriss', 'wilaya_id' => 10 ],
            [ 'id' => '1033', 'name' => 'Bechloul', 'ar_name' => 'بشلول', 'slug' => 'bechloul', 'wilaya_id' => 10 ],
            [ 'id' => '1035', 'name' => 'Ain Bessem', 'ar_name' => 'عين بسام', 'slug' => 'ain-bessem', 'wilaya_id' => 10 ],
            [ 'id' => '1036', 'name' => 'Bir Ghbalou', 'ar_name' => 'بئر غبالو', 'slug' => 'bir-ghbalou', 'wilaya_id' => 10 ],
            [ 'id' => '1037', 'name' => "M'chedallah", 'ar_name' => 'مشد الله', 'slug' => 'mchedallah', 'wilaya_id' => 10 ],
            [ 'id' => '1038', 'name' => 'Sour El Ghozlane', 'ar_name' => 'سور الغزلان', 'slug' => 'sour-el-ghozlane', 'wilaya_id' => 10 ],
            [ 'id' => '1101', 'name' => 'Tamanrasset', 'ar_name' => 'تمنراست', 'slug' => 'tamanrasset', 'wilaya_id' => 11 ],
            [ 'id' => '1102', 'name' => 'Silet', 'ar_name' => 'سيلت', 'slug' => 'silet', 'wilaya_id' => 11 ],
            [ 'id' => '1106', 'name' => 'Tazrouk', 'ar_name' => 'تاظروك', 'slug' => 'tazrouk', 'wilaya_id' => 11 ],
            [ 'id' => '1201', 'name' => 'Tebessa', 'ar_name' => 'تبسة', 'slug' => 'tebessa', 'wilaya_id' => 12 ],
            [ 'id' => '1202', 'name' => 'Bir El Ater', 'ar_name' => 'بئر العاتر', 'slug' => 'bir-el-ater', 'wilaya_id' => 12 ],
            [ 'id' => '1203', 'name' => 'Cheria', 'ar_name' => 'الشريعة', 'slug' => 'cheria', 'wilaya_id' => 12 ],
            [ 'id' => '1205', 'name' => 'El Aouinet', 'ar_name' => 'العوينات', 'slug' => 'el-aouinet', 'wilaya_id' => 12 ],
            [ 'id' => '1209', 'name' => 'Negrine', 'ar_name' => 'نقرين', 'slug' => 'negrine', 'wilaya_id' => 12 ],
            [ 'id' => '1210', 'name' => 'Bir Mokadem', 'ar_name' => 'بئر مقدم', 'slug' => 'bir-mokadem', 'wilaya_id' => 12 ],
            [ 'id' => '1211', 'name' => 'El Kouif', 'ar_name' => 'الكويف', 'slug' => 'el-kouif', 'wilaya_id' => 12 ],
            [ 'id' => '1212', 'name' => 'Morsott', 'ar_name' => 'مرسط', 'slug' => 'morsott', 'wilaya_id' => 12 ],
            [ 'id' => '1213', 'name' => 'El Ogla', 'ar_name' => 'العقلة', 'slug' => 'el-ogla', 'wilaya_id' => 12 ],
            [ 'id' => '1219', 'name' => 'Ouenza', 'ar_name' => 'الونزة', 'slug' => 'ouenza', 'wilaya_id' => 12 ],
            [ 'id' => '1220', 'name' => 'El Malabiod', 'ar_name' => 'الماء الابيض', 'slug' => 'el-malabiod', 'wilaya_id' => 12 ],
            [ 'id' => '1221', 'name' => 'Oum Ali', 'ar_name' => 'أم علي', 'slug' => 'oum-ali', 'wilaya_id' => 12 ],
            [ 'id' => '1301', 'name' => 'Tlemcen', 'ar_name' => 'تلمسان', 'slug' => 'tlemcen', 'wilaya_id' => 13 ],
            [ 'id' => '1303', 'name' => 'Ain Tellout', 'ar_name' => 'عين تالوت', 'slug' => 'ain-tellout', 'wilaya_id' => 13 ],
            [ 'id' => '1304', 'name' => 'Remchi', 'ar_name' => 'الرمشي', 'slug' => 'remchi', 'wilaya_id' => 13 ],
            [ 'id' => '1306', 'name' => 'Sabra', 'ar_name' => 'صبرة', 'slug' => 'sabra', 'wilaya_id' => 13 ],
            [ 'id' => '1307', 'name' => 'Ghazaouet', 'ar_name' => 'الغزوات', 'slug' => 'ghazaouet', 'wilaya_id' => 13 ],
            [ 'id' => '1313', 'name' => 'Ouled Mimoun', 'ar_name' => 'أولاد ميمون', 'slug' => 'ouled-mimoun', 'wilaya_id' => 13 ],
            [ 'id' => '1317', 'name' => 'Beni Snous', 'ar_name' => 'بني سنوس', 'slug' => 'beni-snous', 'wilaya_id' => 13 ],
            [ 'id' => '1318', 'name' => 'Bab El Assa', 'ar_name' => 'باب العسة', 'slug' => 'bab-el-assa', 'wilaya_id' => 13 ],
            [ 'id' => '1320', 'name' => 'Fellaoucene', 'ar_name' => 'فلاوسن', 'slug' => 'fellaoucene', 'wilaya_id' => 13 ],
            [ 'id' => '1324', 'name' => 'Bensekrane', 'ar_name' => 'بن سكران', 'slug' => 'bensekrane', 'wilaya_id' => 13 ],
            [ 'id' => '1326', 'name' => 'Hennaya', 'ar_name' => 'الحناية', 'slug' => 'hennaya', 'wilaya_id' => 13 ],
            [ 'id' => '1327', 'name' => 'Maghnia', 'ar_name' => 'مغنية', 'slug' => 'maghnia', 'wilaya_id' => 13 ],
            [ 'id' => '1335', 'name' => 'Sebdou', 'ar_name' => 'سبدو', 'slug' => 'sebdou', 'wilaya_id' => 13 ],
            [ 'id' => '1338', 'name' => 'Beni Boussaid', 'ar_name' => 'بني بوسعيد', 'slug' => 'beni-boussaid', 'wilaya_id' => 13 ],
            [ 'id' => '1339', 'name' => 'Marsa Ben Mehdi', 'ar_name' => 'مرسى بن مهيدي', 'slug' => 'marsa-ben-mehdi', 'wilaya_id' => 13 ],
            [ 'id' => '1340', 'name' => 'Nedroma', 'ar_name' => 'ندرومة', 'slug' => 'nedroma', 'wilaya_id' => 13 ],
            [ 'id' => '1341', 'name' => 'Sidi Djillali', 'ar_name' => 'سيدي الجيلالي', 'slug' => 'sidi-djillali', 'wilaya_id' => 13 ],
            [ 'id' => '1344', 'name' => 'Honnaine', 'ar_name' => 'هنين', 'slug' => 'honnaine', 'wilaya_id' => 13 ],
            [ 'id' => '1350', 'name' => 'Chetouane', 'ar_name' => 'شتوان', 'slug' => 'chetouane', 'wilaya_id' => 13 ],
            [ 'id' => '1351', 'name' => 'Mansourah', 'ar_name' => 'منصورة', 'slug' => 'mansourah-tlemcen', 'wilaya_id' => 13 ],
            [ 'id' => '1401', 'name' => 'Tiaret', 'ar_name' => 'تيارت', 'slug' => 'tiaret', 'wilaya_id' => 14 ],
            [ 'id' => '1402', 'name' => 'Medroussa', 'ar_name' => 'مدروسة', 'slug' => 'medroussa', 'wilaya_id' => 14 ],
            [ 'id' => '1406', 'name' => 'Ain Deheb', 'ar_name' => 'عين الذهب', 'slug' => 'ain-deheb', 'wilaya_id' => 14 ],
            [ 'id' => '1413', 'name' => 'Dahmouni', 'ar_name' => 'دحموني', 'slug' => 'dahmouni', 'wilaya_id' => 14 ],
            [ 'id' => '1414', 'name' => 'Rahouia', 'ar_name' => 'رحوية', 'slug' => 'rahouia', 'wilaya_id' => 14 ],
            [ 'id' => '1415', 'name' => 'Mahdia', 'ar_name' => 'مهدية', 'slug' => 'mahdia', 'wilaya_id' => 14 ],
            [ 'id' => '1416', 'name' => 'Sougueur', 'ar_name' => 'السوقر', 'slug' => 'sougueur', 'wilaya_id' => 14 ],
            [ 'id' => '1421', 'name' => 'Meghila', 'ar_name' => 'مغيلة', 'slug' => 'meghila', 'wilaya_id' => 14 ],
            [ 'id' => '1427', 'name' => 'Frenda', 'ar_name' => 'فرندة', 'slug' => 'frenda', 'wilaya_id' => 14 ],
            [ 'id' => '1428', 'name' => 'Ain Kermes', 'ar_name' => 'عين كرمس', 'slug' => 'ain-kermes', 'wilaya_id' => 14 ],
            [ 'id' => '1429', 'name' => 'Ksar Chellala', 'ar_name' => 'قصر الشلالة', 'slug' => 'ksar-chellala', 'wilaya_id' => 14 ],
            [ 'id' => '1433', 'name' => 'Oued Lili', 'ar_name' => 'وادي ليلي', 'slug' => 'oued-lili', 'wilaya_id' => 14 ],
            [ 'id' => '1434', 'name' => 'Mechraa Sfa', 'ar_name' => 'مشرع الصفا', 'slug' => 'mechraa-sfa', 'wilaya_id' => 14 ],
            [ 'id' => '1435', 'name' => 'Hamadia', 'ar_name' => 'حمادية', 'slug' => 'hamadia', 'wilaya_id' => 14 ],
            [ 'id' => '1501', 'name' => 'Tizi Ouzou', 'ar_name' => 'تيزي وزو', 'slug' => 'tizi-ouzou', 'wilaya_id' => 15 ],
            [ 'id' => '1502', 'name' => 'Ain El Hammam', 'ar_name' => 'عين الحمام', 'slug' => 'ain-el-hammam', 'wilaya_id' => 15 ],
            [ 'id' => '1509', 'name' => 'Makouda', 'ar_name' => 'ماكودة', 'slug' => 'makouda', 'wilaya_id' => 15 ],
            [ 'id' => '1510', 'name' => 'Draa El Mizan', 'ar_name' => 'ذراع الميزان', 'slug' => 'draa-el-mizan', 'wilaya_id' => 15 ],
            [ 'id' => '1511', 'name' => 'Tizi-Ghenif', 'ar_name' => 'تيزي غنيف', 'slug' => 'tizi-ghenif', 'wilaya_id' => 15 ],
            [ 'id' => '1517', 'name' => 'Iferhounene', 'ar_name' => 'إفرحونان', 'slug' => 'iferhounene', 'wilaya_id' => 15 ],
            [ 'id' => '1518', 'name' => 'Azazga', 'ar_name' => 'عزازقة', 'slug' => 'azazga', 'wilaya_id' => 15 ],
            [ 'id' => '1521', 'name' => 'Larbaa Nath Iraten', 'ar_name' => 'الأربعاء ناث إيراثن', 'slug' => 'larbaa-nath-iraten', 'wilaya_id' => 15 ],
            [ 'id' => '1522', 'name' => 'Tizi Rached', 'ar_name' => 'تيزي راشد', 'slug' => 'tizi-rached', 'wilaya_id' => 15 ],
            [ 'id' => '1524', 'name' => 'Ouaguenoun', 'ar_name' => 'واقنون', 'slug' => 'ouaguenoun', 'wilaya_id' => 15 ],
            [ 'id' => '1529', 'name' => 'Maatkas', 'ar_name' => 'معاتقة', 'slug' => 'maatkas', 'wilaya_id' => 15 ],
            [ 'id' => '1532', 'name' => 'Beni Douala', 'ar_name' => 'بني دوالة', 'slug' => 'beni-douala', 'wilaya_id' => 15 ],
            [ 'id' => '1534', 'name' => 'Bouzeguene', 'ar_name' => 'بوزقن', 'slug' => 'bouzeguene', 'wilaya_id' => 15 ],
            [ 'id' => '1536', 'name' => 'Ouadhias', 'ar_name' => 'واضية', 'slug' => 'ouadhias', 'wilaya_id' => 15 ],
            [ 'id' => '1537', 'name' => 'Azeffoun', 'ar_name' => 'أزفون', 'slug' => 'azeffoun', 'wilaya_id' => 15 ],
            [ 'id' => '1538', 'name' => 'Tigzirt', 'ar_name' => 'تيقزيرت', 'slug' => 'tigzirt', 'wilaya_id' => 15 ],
            [ 'id' => '1540', 'name' => 'Boghni', 'ar_name' => 'بوغني', 'slug' => 'boghni', 'wilaya_id' => 15 ],
            [ 'id' => '1547', 'name' => 'Draa Ben Khedda', 'ar_name' => 'ذراع بن خدة', 'slug' => 'draa-ben-khedda', 'wilaya_id' => 15 ],
            [ 'id' => '1548', 'name' => 'Ouacif', 'ar_name' => 'واسيف', 'slug' => 'ouacif', 'wilaya_id' => 15 ],
            [ 'id' => '1550', 'name' => 'Mekla', 'ar_name' => 'مقلع', 'slug' => 'mekla', 'wilaya_id' => 15 ],
            [ 'id' => '1552', 'name' => 'Benni Yenni', 'ar_name' => 'بني يني', 'slug' => 'benni-yenni', 'wilaya_id' => 15 ],
            [ 'id' => '1602', 'name' => "Sidi M'hamed", 'ar_name' => 'سيدي امحمد', 'slug' => 'sidi-mhamed', 'wilaya_id' => 16 ],
            [ 'id' => '1605', 'name' => 'Bab El Oued', 'ar_name' => 'باب الوادي', 'slug' => 'bab-el-oued', 'wilaya_id' => 16 ],
            [ 'id' => '1609', 'name' => 'Bir Mourad Rais', 'ar_name' => 'بئر مراد رايس', 'slug' => 'bir-mourad-rais', 'wilaya_id' => 16 ],
            [ 'id' => '1611', 'name' => 'Bouzareah', 'ar_name' => 'بوزريعة', 'slug' => 'bouzareah', 'wilaya_id' => 16 ],
            [ 'id' => '1613', 'name' => 'El Harrach', 'ar_name' => 'الحراش', 'slug' => 'el-harrach', 'wilaya_id' => 16 ],
            [ 'id' => '1614', 'name' => 'Baraki', 'ar_name' => 'براقي', 'slug' => 'baraki', 'wilaya_id' => 16 ],
            [ 'id' => '1617', 'name' => 'Hussein Dey', 'ar_name' => 'حسين داي', 'slug' => 'hussein-dey', 'wilaya_id' => 16 ],
            [ 'id' => '1620', 'name' => 'Dar El Beida', 'ar_name' => 'الدار البيضاء', 'slug' => 'dar-el-beida', 'wilaya_id' => 16 ],
            [ 'id' => '1636', 'name' => 'Birtouta', 'ar_name' => 'بئر توتة', 'slug' => 'birtouta', 'wilaya_id' => 16 ],
            [ 'id' => '1638', 'name' => 'Rouiba', 'ar_name' => 'الرويبة', 'slug' => 'rouiba', 'wilaya_id' => 16 ],
            [ 'id' => '1644', 'name' => 'Zeralda', 'ar_name' => 'زرالدة', 'slug' => 'zeralda', 'wilaya_id' => 16 ],
            [ 'id' => '1649', 'name' => 'Draria', 'ar_name' => 'الدرارية', 'slug' => 'draria', 'wilaya_id' => 16 ],
            [ 'id' => '1652', 'name' => 'Cheraga', 'ar_name' => 'الشراقة', 'slug' => 'cheraga', 'wilaya_id' => 16 ],
            [ 'id' => '1701', 'name' => 'Djelfa', 'ar_name' => 'الجلفة', 'slug' => 'djelfa', 'wilaya_id' => 17 ],
            [ 'id' => '1704', 'name' => 'Hassi Bahbah', 'ar_name' => 'حاسي بحبح', 'slug' => 'hassi-bahbah', 'wilaya_id' => 17 ],
            [ 'id' => '1707', 'name' => 'Faidh El Botma', 'ar_name' => 'فيض البطمة', 'slug' => 'faidh-el-botma', 'wilaya_id' => 17 ],
            [ 'id' => '1708', 'name' => 'Birine', 'ar_name' => 'بيرين', 'slug' => 'birine', 'wilaya_id' => 17 ],
            [ 'id' => '1714', 'name' => 'El Idrissia', 'ar_name' => 'الادريسية', 'slug' => 'el-idrissia', 'wilaya_id' => 17 ],
            [ 'id' => '1717', 'name' => 'Messaad', 'ar_name' => 'مسعد', 'slug' => 'messaad', 'wilaya_id' => 17 ],
            [ 'id' => '1719', 'name' => 'Sidi Laadjel', 'ar_name' => 'سيدي لعجال', 'slug' => 'sidi-laadjel', 'wilaya_id' => 17 ],
            [ 'id' => '1720', 'name' => 'Had Sahary', 'ar_name' => 'حد الصحاري', 'slug' => 'had-sahary', 'wilaya_id' => 17 ],
            [ 'id' => '1725', 'name' => 'Dar Chioukh', 'ar_name' => 'دار الشيوخ', 'slug' => 'dar-chioukh', 'wilaya_id' => 17 ],
            [ 'id' => '1726', 'name' => 'Charef', 'ar_name' => 'الشارف', 'slug' => 'charef', 'wilaya_id' => 17 ],
            [ 'id' => '1730', 'name' => 'Ain El Ibel', 'ar_name' => 'عين الإبل', 'slug' => 'ain-el-ibel', 'wilaya_id' => 17 ],
            [ 'id' => '1731', 'name' => 'Ain Oussera', 'ar_name' => 'عين وسارة', 'slug' => 'ain-oussera', 'wilaya_id' => 17 ],
            [ 'id' => '1801', 'name' => 'Jijel', 'ar_name' => 'جيجل', 'slug' => 'jijel', 'wilaya_id' => 18 ],
            [ 'id' => '1803', 'name' => 'El Aouana', 'ar_name' => 'العوانة', 'slug' => 'el-aouana', 'wilaya_id' => 18 ],
            [ 'id' => '1804', 'name' => 'Ziamah Mansouriah', 'ar_name' => 'زيامة منصورية', 'slug' => 'ziamah-mansouriah', 'wilaya_id' => 18 ],
            [ 'id' => '1805', 'name' => 'Taher', 'ar_name' => 'الطاهير', 'slug' => 'taher', 'wilaya_id' => 18 ],
            [ 'id' => '1807', 'name' => 'Chekfa', 'ar_name' => 'الشقفة', 'slug' => 'chekfa', 'wilaya_id' => 18 ],
            [ 'id' => '1809', 'name' => 'El Milia', 'ar_name' => 'الميلية', 'slug' => 'el-milia', 'wilaya_id' => 18 ],
            [ 'id' => '1810', 'name' => 'Sidi Marouf', 'ar_name' => 'سيدي معروف', 'slug' => 'sidi-marouf', 'wilaya_id' => 18 ],
            [ 'id' => '1811', 'name' => 'Settara', 'ar_name' => 'السطارة', 'slug' => 'settara', 'wilaya_id' => 18 ],
            [ 'id' => '1812', 'name' => 'El Ancer', 'ar_name' => 'العنصر', 'slug' => 'el-ancer', 'wilaya_id' => 18 ],
            [ 'id' => '1817', 'name' => 'Djimla', 'ar_name' => 'جيملة', 'slug' => 'djimla', 'wilaya_id' => 18 ],
            [ 'id' => '1824', 'name' => 'Texenna', 'ar_name' => 'تاكسنة', 'slug' => 'texenna', 'wilaya_id' => 18 ],
            [ 'id' => '1901', 'name' => 'Setif', 'ar_name' => 'سطيف', 'slug' => 'setif', 'wilaya_id' => 19 ],
            [ 'id' => '1902', 'name' => 'Ain El Kebira', 'ar_name' => 'عين الكبيرة', 'slug' => 'ain-el-kebira', 'wilaya_id' => 19 ],
            [ 'id' => '1903', 'name' => 'Beni Aziz', 'ar_name' => 'بني عزيز', 'slug' => 'beni-aziz', 'wilaya_id' => 19 ],
            [ 'id' => '1908', 'name' => 'Bir El Arch', 'ar_name' => 'بئر العرش', 'slug' => 'bir-el-arch', 'wilaya_id' => 19 ],
            [ 'id' => '1916', 'name' => 'Babor', 'ar_name' => 'بابور', 'slug' => 'babor', 'wilaya_id' => 19 ],
            [ 'id' => '1917', 'name' => 'Guidjel', 'ar_name' => 'قجال', 'slug' => 'guidjel', 'wilaya_id' => 19 ],
            [ 'id' => '1920', 'name' => 'El Eulma', 'ar_name' => 'العلمة', 'slug' => 'el-eulma', 'wilaya_id' => 19 ],
            [ 'id' => '1921', 'name' => 'Djemila', 'ar_name' => 'جميلة', 'slug' => 'djemila', 'wilaya_id' => 19 ],
            [ 'id' => '1922', 'name' => 'Beni Ourtilane', 'ar_name' => 'بني ورتيلان', 'slug' => 'beni-ourtilane', 'wilaya_id' => 19 ],
            [ 'id' => '1926', 'name' => 'Ain Arnat', 'ar_name' => 'عين أرنات', 'slug' => 'ain-arnat', 'wilaya_id' => 19 ],
            [ 'id' => '1927', 'name' => 'Amoucha', 'ar_name' => 'عموشة', 'slug' => 'amoucha', 'wilaya_id' => 19 ],
            [ 'id' => '1928', 'name' => 'Ain Oulmene', 'ar_name' => 'عين ولمان', 'slug' => 'ain-oulmene', 'wilaya_id' => 19 ],
            [ 'id' => '1930', 'name' => 'Bouandas', 'ar_name' => 'بوعنداس', 'slug' => 'bouandas', 'wilaya_id' => 19 ],
            [ 'id' => '1932', 'name' => 'Hammam Sokhna', 'ar_name' => 'حمام السخنة', 'slug' => 'hammam-sokhna', 'wilaya_id' => 19 ],
            [ 'id' => '1939', 'name' => 'Salah Bey', 'ar_name' => 'صالح باي', 'slug' => 'salah-bey', 'wilaya_id' => 19 ],
            [ 'id' => '1940', 'name' => 'Ain Azel', 'ar_name' => 'عين أزال', 'slug' => 'ain-azel', 'wilaya_id' => 19 ],
            [ 'id' => '1941', 'name' => 'Guenzet', 'ar_name' => 'قنزات', 'slug' => 'guenzet', 'wilaya_id' => 19 ],
            [ 'id' => '1943', 'name' => 'Bougaa', 'ar_name' => 'بوقاعة', 'slug' => 'bougaa', 'wilaya_id' => 19 ],
            [ 'id' => '1950', 'name' => 'Hammam Guergour', 'ar_name' => 'حمام قرقور', 'slug' => 'hammam-guergour', 'wilaya_id' => 19 ],
            [ 'id' => '1955', 'name' => 'Maoklane', 'ar_name' => 'ماوكلان', 'slug' => 'maoklane', 'wilaya_id' => 19 ],
            [ 'id' => '2001', 'name' => 'Saida', 'ar_name' => 'سعيدة', 'slug' => 'saida', 'wilaya_id' => 20 ],
            [ 'id' => '2003', 'name' => 'Ain El Hadjar', 'ar_name' => 'عين الحجر', 'slug' => 'ain-el-hadjar', 'wilaya_id' => 20 ],
            [ 'id' => '2006', 'name' => 'Youb', 'ar_name' => 'يوب', 'slug' => 'youb', 'wilaya_id' => 20 ],
            [ 'id' => '2009', 'name' => 'Sidi Boubekeur', 'ar_name' => 'سيدي بوبكر', 'slug' => 'sidi-boubekeur', 'wilaya_id' => 20 ],
            [ 'id' => '2010', 'name' => 'El Hassasna', 'ar_name' => 'الحساسنة', 'slug' => 'el-hassasna', 'wilaya_id' => 20 ],
            [ 'id' => '2014', 'name' => 'Ouled Brahim', 'ar_name' => 'أولاد ابراهيم', 'slug' => 'ouled-brahim', 'wilaya_id' => 20 ],
            [ 'id' => '2101', 'name' => 'Skikda', 'ar_name' => 'سكيكدة', 'slug' => 'skikda', 'wilaya_id' => 21 ],
            [ 'id' => '2103', 'name' => 'El Hadaiek', 'ar_name' => 'الحدائق', 'slug' => 'el-hadaiek', 'wilaya_id' => 21 ],
            [ 'id' => '2104', 'name' => 'Azzaba', 'ar_name' => 'عزابة', 'slug' => 'azzaba', 'wilaya_id' => 21 ],
            [ 'id' => '2108', 'name' => 'Ben Azzouz', 'ar_name' => 'بن عزوز', 'slug' => 'ben-azzouz', 'wilaya_id' => 21 ],
            [ 'id' => '2110', 'name' => 'Collo', 'ar_name' => 'القل', 'slug' => 'collo', 'wilaya_id' => 21 ],
            [ 'id' => '2113', 'name' => 'Ouled Attia', 'ar_name' => 'أولاد عطية', 'slug' => 'ouled-attia', 'wilaya_id' => 21 ],
            [ 'id' => '2115', 'name' => 'Zitouna', 'ar_name' => 'الزيتونة', 'slug' => 'zitouna', 'wilaya_id' => 21 ],
            [ 'id' => '2116', 'name' => 'El Harrouch', 'ar_name' => 'الحروش', 'slug' => 'el-harrouch', 'wilaya_id' => 21 ],
            [ 'id' => '2119', 'name' => 'Sidi Mezghiche', 'ar_name' => 'سيدي مزغيش', 'slug' => 'sidi-mezghiche', 'wilaya_id' => 21 ],
            [ 'id' => '2123', 'name' => 'Ramdane Djamel', 'ar_name' => 'رمضان جمال', 'slug' => 'ramdane-djamel', 'wilaya_id' => 21 ],
            [ 'id' => '2126', 'name' => 'Tamalous', 'ar_name' => 'تمالوس', 'slug' => 'tamalous', 'wilaya_id' => 21 ],
            [ 'id' => '2127', 'name' => 'Ain Kechra', 'ar_name' => 'عين قشرة', 'slug' => 'ain-kechra', 'wilaya_id' => 21 ],
            [ 'id' => '2128', 'name' => 'Oum Toub', 'ar_name' => 'أم الطوب', 'slug' => 'oum-toub', 'wilaya_id' => 21 ],
            [ 'id' => '2201', 'name' => 'Sidi Bel Abbes', 'ar_name' => 'سيدي بلعباس', 'slug' => 'sidi-bel-abbes', 'wilaya_id' => 22 ],
            [ 'id' => '2202', 'name' => 'Tessala', 'ar_name' => 'تسالة', 'slug' => 'tessala', 'wilaya_id' => 22 ],
            [ 'id' => '2204', 'name' => 'Mostefa Ben Brahim', 'ar_name' => 'مصطفى بن ابراهيم', 'slug' => 'mostefa-ben-brahim', 'wilaya_id' => 22 ],
            [ 'id' => '2205', 'name' => 'Telagh', 'ar_name' => 'تلاغ', 'slug' => 'telagh', 'wilaya_id' => 22 ],
            [ 'id' => '2208', 'name' => 'Sidi Ali Boussidi', 'ar_name' => 'سيدي علي بوسيدي', 'slug' => 'sidi-ali-boussidi', 'wilaya_id' => 22 ],
            [ 'id' => '2210', 'name' => 'Marhoum', 'ar_name' => 'مرحوم', 'slug' => 'marhoum', 'wilaya_id' => 22 ],
            [ 'id' => '2214', 'name' => 'Sidi Lahcene', 'ar_name' => 'سيدي لحسن', 'slug' => 'sidi-lahcene', 'wilaya_id' => 22 ],
            [ 'id' => '2217', 'name' => 'Tenira', 'ar_name' => 'تنيرة', 'slug' => 'tenira', 'wilaya_id' => 22 ],
            [ 'id' => '2218', 'name' => 'Moulay Slissen', 'ar_name' => 'مولاي سليسن', 'slug' => 'moulay-slissen', 'wilaya_id' => 22 ],
            [ 'id' => '2222', 'name' => 'Merine', 'ar_name' => 'مرين', 'slug' => 'merine', 'wilaya_id' => 22 ],
            [ 'id' => '2223', 'name' => 'Ras El Ma', 'ar_name' => 'راس الماء', 'slug' => 'ras-el-ma', 'wilaya_id' => 22 ],
            [ 'id' => '2228', 'name' => 'Ain El Berd', 'ar_name' => 'عين البرد', 'slug' => 'ain-el-berd', 'wilaya_id' => 22 ],
            [ 'id' => '2229', 'name' => 'Sfisef', 'ar_name' => 'سفيزف', 'slug' => 'sfisef', 'wilaya_id' => 22 ],
            [ 'id' => '2245', 'name' => 'Ben Badis', 'ar_name' => 'بن باديس', 'slug' => 'ben-badis', 'wilaya_id' => 22 ],
            [ 'id' => '2246', 'name' => 'Sidi Ali Ben Youb', 'ar_name' => 'سيدي علي بن يوب', 'slug' => 'sidi-ali-ben-youb', 'wilaya_id' => 22 ],
            [ 'id' => '2301', 'name' => 'Annaba', 'ar_name' => 'عنابة', 'slug' => 'annaba', 'wilaya_id' => 23 ],
            [ 'id' => '2302', 'name' => 'Berrahal', 'ar_name' => 'برحال', 'slug' => 'berrahal', 'wilaya_id' => 23 ],
            [ 'id' => '2303', 'name' => 'El Hadjar', 'ar_name' => 'الحجار', 'slug' => 'el-hadjar', 'wilaya_id' => 23 ],
            [ 'id' => '2305', 'name' => 'El Bouni', 'ar_name' => 'البوني', 'slug' => 'el-bouni', 'wilaya_id' => 23 ],
            [ 'id' => '2309', 'name' => 'Ain El Berda', 'ar_name' => 'عين الباردة', 'slug' => 'ain-el-berda', 'wilaya_id' => 23 ],
            [ 'id' => '2310', 'name' => 'Chetaibi', 'ar_name' => 'شطايبي', 'slug' => 'chetaibi', 'wilaya_id' => 23 ],
            [ 'id' => '2401', 'name' => 'Guelma', 'ar_name' => 'قالمة', 'slug' => 'guelma', 'wilaya_id' => 24 ],
            [ 'id' => '2404', 'name' => 'Oued Zenati', 'ar_name' => 'وادي الزناتي', 'slug' => 'oued-zenati', 'wilaya_id' => 24 ],
            [ 'id' => '2413', 'name' => 'Ain Makhlouf', 'ar_name' => 'عين مخلوف', 'slug' => 'ain-makhlouf', 'wilaya_id' => 24 ],
            [ 'id' => '2415', 'name' => 'Khezaras', 'ar_name' => 'خزارة', 'slug' => 'khezaras', 'wilaya_id' => 24 ],
            [ 'id' => '2418', 'name' => 'Guelaat Bousbaa', 'ar_name' => 'قلعة بوصبع', 'slug' => 'guelaat-bousbaa', 'wilaya_id' => 24 ],
            [ 'id' => '2419', 'name' => 'Hammam Debagh', 'ar_name' => 'حمام دباغ', 'slug' => 'hammam-debagh', 'wilaya_id' => 24 ],
            [ 'id' => '2422', 'name' => "Hammam N'bails", 'ar_name' => 'حمام النبايل', 'slug' => 'hammam-nbails', 'wilaya_id' => 24 ],
            [ 'id' => '2425', 'name' => 'Bouchegouf', 'ar_name' => 'بوشقوف', 'slug' => 'bouchegouf', 'wilaya_id' => 24 ],
            [ 'id' => '2426', 'name' => 'Heliopolis', 'ar_name' => 'هيليوبوليس', 'slug' => 'heliopolis', 'wilaya_id' => 24 ],
            [ 'id' => '2427', 'name' => 'Ain Hessainia', 'ar_name' => 'عين حساينية', 'slug' => 'ain-hessaina', 'wilaya_id' => 24 ],
            [ 'id' => '2501', 'name' => 'Constantine', 'ar_name' => 'قسنطينة', 'slug' => 'constantine', 'wilaya_id' => 25 ],
            [ 'id' => '2502', 'name' => 'Hamma Bouziane', 'ar_name' => 'حامة بوزيان', 'slug' => 'hamma-bouziane', 'wilaya_id' => 25 ],
            [ 'id' => '2504', 'name' => 'Zighoud Youcef', 'ar_name' => 'زيغود يوسف', 'slug' => 'zighoud-youcef', 'wilaya_id' => 25 ],
            [ 'id' => '2506', 'name' => 'El Khroub', 'ar_name' => 'الخروب', 'slug' => 'el-khroub', 'wilaya_id' => 25 ],
            [ 'id' => '2507', 'name' => 'Ain Abid', 'ar_name' => 'عين عبيد', 'slug' => 'ain-abid', 'wilaya_id' => 25 ],
            [ 'id' => '2512', 'name' => 'Ibn Ziad', 'ar_name' => 'ابن زياد', 'slug' => 'ibn-ziad', 'wilaya_id' => 25 ],
            [ 'id' => '2601', 'name' => 'Medea', 'ar_name' => 'المدية', 'slug' => 'medea', 'wilaya_id' => 26 ],
            [ 'id' => '2602', 'name' => 'Ouzera', 'ar_name' => 'وزرة', 'slug' => 'ouzera', 'wilaya_id' => 26 ],
            [ 'id' => '2604', 'name' => 'Ain Boucif', 'ar_name' => 'عين بوسيف', 'slug' => 'ain-boucif', 'wilaya_id' => 26 ],
            [ 'id' => '2607', 'name' => 'El Omaria', 'ar_name' => 'العمارية', 'slug' => 'el-omaria', 'wilaya_id' => 26 ],
            [ 'id' => '2609', 'name' => 'Guelb El Kebir', 'ar_name' => 'القلب الكبير', 'slug' => 'guelb-el-kebir', 'wilaya_id' => 26 ],
            [ 'id' => '2618', 'name' => 'Chellalat El Adhaoura', 'ar_name' => 'شلالة العذاورة', 'slug' => 'chellalat-el-adhaoura', 'wilaya_id' => 26 ],
            [ 'id' => '2626', 'name' => 'Sidi Naamane', 'ar_name' => 'سيدي نعمان', 'slug' => 'sidi-naamane', 'wilaya_id' => 26 ],
            [ 'id' => '2632', 'name' => 'Aziz', 'ar_name' => 'عزيز', 'slug' => 'aziz', 'wilaya_id' => 26 ],
            [ 'id' => '2633', 'name' => 'Souaghi', 'ar_name' => 'السواقي', 'slug' => 'souaghi', 'wilaya_id' => 26 ],
            [ 'id' => '2635', 'name' => 'Ksar El Boukhari', 'ar_name' => 'قصر البخاري', 'slug' => 'ksar-el-boukhari', 'wilaya_id' => 26 ],
            [ 'id' => '2636', 'name' => 'El Azizia', 'ar_name' => 'العزيزية', 'slug' => 'el-azizia', 'wilaya_id' => 26 ],
            [ 'id' => '2638', 'name' => 'Chahbounia', 'ar_name' => 'الشهبونية', 'slug' => 'chahbounia', 'wilaya_id' => 26 ],
            [ 'id' => '2643', 'name' => 'Ouamri', 'ar_name' => 'عوامري', 'slug' => 'ouamri', 'wilaya_id' => 26 ],
            [ 'id' => '2644', 'name' => 'Si Mahdjoub', 'ar_name' => 'سي المحجوب', 'slug' => 'si-mahdjoub', 'wilaya_id' => 26 ],
            [ 'id' => '2646', 'name' => 'Beni Slimane', 'ar_name' => 'بني سليمان', 'slug' => 'beni-slimane', 'wilaya_id' => 26 ],
            [ 'id' => '2647', 'name' => 'Berrouaghia', 'ar_name' => 'البرواقية', 'slug' => 'berrouaghnia', 'wilaya_id' => 26 ],
            [ 'id' => '2648', 'name' => 'Seghouane', 'ar_name' => 'سغوان', 'slug' => 'seghouane', 'wilaya_id' => 26 ],
            [ 'id' => '2652', 'name' => 'Tablat', 'ar_name' => 'تابلاط', 'slug' => 'tablat', 'wilaya_id' => 26 ],
            [ 'id' => '2658', 'name' => 'Ouled Antar', 'ar_name' => 'أولاد عنتر', 'slug' => 'ouled-antar', 'wilaya_id' => 26 ],
            [ 'id' => '2701', 'name' => 'Mostaganem', 'ar_name' => 'مستغانم', 'slug' => 'mostaganem', 'wilaya_id' => 27 ],
            [ 'id' => '2705', 'name' => 'Ain Nouicy', 'ar_name' => 'عين نويسي', 'slug' => 'ain-nouicy', 'wilaya_id' => 27 ],
            [ 'id' => '2706', 'name' => 'Hassi Mameche', 'ar_name' => 'حاسي ماماش', 'slug' => 'hassi-mameche', 'wilaya_id' => 27 ],
            [ 'id' => '2707', 'name' => 'Ain Tedeles', 'ar_name' => 'عين تادلس', 'slug' => 'ain-tedeles', 'wilaya_id' => 27 ],
            [ 'id' => '2711', 'name' => 'Kheir Eddine', 'ar_name' => 'خير الدين', 'slug' => 'kheir-eddine', 'wilaya_id' => 27 ],
            [ 'id' => '2712', 'name' => 'Sidi Ali', 'ar_name' => 'سيدي علي', 'slug' => 'sidi-ali', 'wilaya_id' => 27 ],
            [ 'id' => '2716', 'name' => 'Sidi Lakhdar', 'ar_name' => 'سيدي لخضر', 'slug' => 'sidi-lakhdar', 'wilaya_id' => 27 ],
            [ 'id' => '2717', 'name' => 'Achaacha', 'ar_name' => 'عشعاشة', 'slug' => 'achaacha', 'wilaya_id' => 27 ],
            [ 'id' => '2719', 'name' => 'Bouguirat', 'ar_name' => 'بوقيراط', 'slug' => 'bouguirat', 'wilaya_id' => 27 ],
            [ 'id' => '2722', 'name' => 'Mesra', 'ar_name' => 'ماسرة', 'slug' => 'mesra', 'wilaya_id' => 27 ],
            [ 'id' => '2801', 'name' => "M'sila", 'ar_name' => 'المسيلة', 'slug' => 'msila', 'wilaya_id' => 28 ],
            [ 'id' => '2803', 'name' => 'Hammam Dalaa', 'ar_name' => 'حمام الضلعة', 'slug' => 'hammam-dalaa', 'wilaya_id' => 28 ],
            [ 'id' => '2804', 'name' => 'Ouled Derradj', 'ar_name' => 'أولاد دراج', 'slug' => 'ouled-derradj', 'wilaya_id' => 28 ],
            [ 'id' => '2807', 'name' => 'Khoubana', 'ar_name' => 'خبانة', 'slug' => 'khoubana', 'wilaya_id' => 28 ],
            [ 'id' => '2809', 'name' => 'Chellal', 'ar_name' => 'شلال', 'slug' => 'chellal', 'wilaya_id' => 28 ],
            [ 'id' => '2811', 'name' => 'Magra', 'ar_name' => 'مقرة', 'slug' => 'magra', 'wilaya_id' => 28 ],
            [ 'id' => '2816', 'name' => 'Sidi Aissa', 'ar_name' => 'سيدي عيسى', 'slug' => 'sidi-aissa', 'wilaya_id' => 28 ],
            [ 'id' => '2817', 'name' => 'Ain El Hadjel', 'ar_name' => 'عين الحجل', 'slug' => 'ain-el-hadjel', 'wilaya_id' => 28 ],
            [ 'id' => '2820', 'name' => 'Bousaada', 'ar_name' => 'بوسعادة', 'slug' => 'bousaada', 'wilaya_id' => 28 ],
            [ 'id' => '2821', 'name' => 'Ouled Sidi Brahim', 'ar_name' => 'أولاد سيدي ابراهيم', 'slug' => 'ouled-sidi-brahim', 'wilaya_id' => 28 ],
            [ 'id' => '2822', 'name' => 'Sidi Ameur', 'ar_name' => 'سيدي عامر', 'slug' => 'sidi-ameur', 'wilaya_id' => 28 ],
            [ 'id' => '2824', 'name' => 'Ben Srour', 'ar_name' => 'بن سرور', 'slug' => 'ben-srour', 'wilaya_id' => 28 ],
            [ 'id' => '2841', 'name' => 'Ain El Melh', 'ar_name' => 'عين الملح', 'slug' => 'ain-el-melh', 'wilaya_id' => 28 ],
            [ 'id' => '2842', 'name' => 'Medjedel', 'ar_name' => 'امجدل', 'slug' => 'medjedel', 'wilaya_id' => 28 ],
            [ 'id' => '2847', 'name' => 'Djebel Messaad', 'ar_name' => 'جبل مساعد', 'slug' => 'djebel-messaad', 'wilaya_id' => 28 ],
            [ 'id' => '2901', 'name' => 'Mascara', 'ar_name' => 'معسكر', 'slug' => 'mascara', 'wilaya_id' => 29 ],
            [ 'id' => '2902', 'name' => 'Bouhanifia', 'ar_name' => 'بوحنيفية', 'slug' => 'bouhanifia', 'wilaya_id' => 29 ],
            [ 'id' => '2903', 'name' => 'Tizi', 'ar_name' => 'تيزي', 'slug' => 'tizi', 'wilaya_id' => 29 ],
            [ 'id' => '2906', 'name' => 'Tighennif', 'ar_name' => 'تيغنيف', 'slug' => 'tighennif', 'wilaya_id' => 29 ],
            [ 'id' => '2907', 'name' => 'Hachem', 'ar_name' => 'الحشم', 'slug' => 'hachem', 'wilaya_id' => 29 ],
            [ 'id' => '2910', 'name' => 'Oued El Abtal', 'ar_name' => 'وادي الأبطال', 'slug' => 'oued-el-abtal', 'wilaya_id' => 29 ],
            [ 'id' => '2912', 'name' => 'Ghriss', 'ar_name' => 'غريس', 'slug' => 'ghriss', 'wilaya_id' => 29 ],
            [ 'id' => '2917', 'name' => 'El Bordj', 'ar_name' => 'البرج', 'slug' => 'el-bordj', 'wilaya_id' => 29 ],
            [ 'id' => '2918', 'name' => 'Ain Fekan', 'ar_name' => 'عين فكان', 'slug' => 'ain-fekan', 'wilaya_id' => 29 ],
            [ 'id' => '2922', 'name' => 'Oued Taria', 'ar_name' => 'وادي التاغية', 'slug' => 'oued-taria', 'wilaya_id' => 29 ],
            [ 'id' => '2923', 'name' => 'Aouf', 'ar_name' => 'عوف', 'slug' => 'aouf', 'wilaya_id' => 29 ],
            [ 'id' => '2924', 'name' => 'Ain Fares', 'ar_name' => 'عين فارس', 'slug' => 'ain-fares', 'wilaya_id' => 29 ],
            [ 'id' => '2926', 'name' => 'Sig', 'ar_name' => 'سيق', 'slug' => 'sig', 'wilaya_id' => 29 ],
            [ 'id' => '2927', 'name' => 'Oggaz', 'ar_name' => 'عقاز', 'slug' => 'oggaz', 'wilaya_id' => 29 ],
            [ 'id' => '2930', 'name' => 'Zahana', 'ar_name' => 'زهانة', 'slug' => 'zahana', 'wilaya_id' => 29 ],
            [ 'id' => '2931', 'name' => 'Mohammadia', 'ar_name' => 'المحمدية', 'slug' => 'mohammadia', 'wilaya_id' => 29 ],
            [ 'id' => '3001', 'name' => 'Ouargla', 'ar_name' => 'ورقلة', 'slug' => 'ouargla', 'wilaya_id' => 30 ],
            [ 'id' => '3003', 'name' => "N'goussa", 'ar_name' => 'انقوسة', 'slug' => 'ngoussa', 'wilaya_id' => 30 ],
            [ 'id' => '3004', 'name' => 'Hassi Messaoud', 'ar_name' => 'حاسي مسعود', 'slug' => 'hassi-messaoud', 'wilaya_id' => 30 ],
            [ 'id' => '3011', 'name' => 'Sidi Khouiled', 'ar_name' => 'سيدي خويلد', 'slug' => 'sidi-khouiled', 'wilaya_id' => 30 ],
            [ 'id' => '3021', 'name' => 'El Borma', 'ar_name' => 'البرمة', 'slug' => 'el-borma', 'wilaya_id' => 30 ],
            [ 'id' => '3101', 'name' => 'Oran', 'ar_name' => 'وهران', 'slug' => 'oran', 'wilaya_id' => 31 ],
            [ 'id' => '3102', 'name' => 'Gdyel', 'ar_name' => 'قديل', 'slug' => 'gdyel', 'wilaya_id' => 31 ],
            [ 'id' => '3103', 'name' => 'Bir El Djir', 'ar_name' => 'بئر الجير', 'slug' => 'bir-el-djir', 'wilaya_id' => 31 ],
            [ 'id' => '3105', 'name' => 'Es Senia', 'ar_name' => 'السانية', 'slug' => 'es-senia', 'wilaya_id' => 31 ],
            [ 'id' => '3106', 'name' => 'Arzew', 'ar_name' => 'أرزيو', 'slug' => 'arzew', 'wilaya_id' => 31 ],
            [ 'id' => '3107', 'name' => 'Bethioua', 'ar_name' => 'بطيوة', 'slug' => 'bethioua', 'wilaya_id' => 31 ],
            [ 'id' => '3109', 'name' => 'Ain Turk', 'ar_name' => 'عين الترك', 'slug' => 'ain-turk', 'wilaya_id' => 31 ],
            [ 'id' => '3111', 'name' => 'Oued Tlelat', 'ar_name' => 'وادي تليلات', 'slug' => 'oued-tlelat', 'wilaya_id' => 31 ],
            [ 'id' => '3124', 'name' => 'Boutlelis', 'ar_name' => 'بوتليليس', 'slug' => 'boutlelis', 'wilaya_id' => 31 ],
            [ 'id' => '3201', 'name' => 'El Bayadh', 'ar_name' => 'البيض', 'slug' => 'el-bayadh', 'wilaya_id' => 32 ],
            [ 'id' => '3202', 'name' => 'Rogassa', 'ar_name' => 'رقاصة', 'slug' => 'rogassa', 'wilaya_id' => 32 ],
            [ 'id' => '3203', 'name' => 'Brezina', 'ar_name' => 'بريزينة', 'slug' => 'brezina', 'wilaya_id' => 32 ],
            [ 'id' => '3205', 'name' => 'Labiodh Sidi Cheikh', 'ar_name' => 'الأبيض سيدي الشيخ', 'slug' => 'labiodh-sidi-cheikh', 'wilaya_id' => 32 ],
            [ 'id' => '3206', 'name' => 'Bougtoub', 'ar_name' => 'بوقطب', 'slug' => 'bougtoub', 'wilaya_id' => 32 ],
            [ 'id' => '3208', 'name' => 'Chellala', 'ar_name' => 'شلالة', 'slug' => 'chellala', 'wilaya_id' => 32 ],
            [ 'id' => '3207', 'name' => 'Boussemghoun', 'ar_name' => 'بوسمغون', 'slug' => 'boussemghoun', 'wilaya_id' => 32 ],
            [ 'id' => '3204', 'name' => 'Boualem', 'ar_name' => 'بوعلام', 'slug' => 'boualem', 'wilaya_id' => 32 ],
            [ 'id' => '3301', 'name' => 'Illizi', 'ar_name' => 'إيليزي', 'slug' => 'illizi', 'wilaya_id' => 33 ],
            [ 'id' => '3306', 'name' => 'In Amenas', 'ar_name' => 'إن أمناس', 'slug' => 'in-amenas', 'wilaya_id' => 33 ],
            [ 'id' => '3401', 'name' => 'Bordj Bou Arreridj', 'ar_name' => 'برج بوعريريج', 'slug' => 'bordj-bou-arreridj', 'wilaya_id' => 34 ],
            [ 'id' => '3402', 'name' => 'Ras El Oued', 'ar_name' => 'رأس الوادي', 'slug' => 'ras-el-oued', 'wilaya_id' => 34 ],
            [ 'id' => '3403', 'name' => 'Bordj Zemmoura', 'ar_name' => 'برج زمورة', 'slug' => 'bordj-zemmoura', 'wilaya_id' => 34 ],
            [ 'id' => '3404', 'name' => 'Mansourah', 'ar_name' => 'المنصورة', 'slug' => 'mansourah-bordj', 'wilaya_id' => 34 ],
            [ 'id' => '3408', 'name' => 'Ain Taghrout', 'ar_name' => 'عين تاغروت', 'slug' => 'ain-taghrout', 'wilaya_id' => 34 ],
            [ 'id' => '3409', 'name' => 'Bordj Ghedir', 'ar_name' => 'برج الغدير', 'slug' => 'bordj-ghedir', 'wilaya_id' => 34 ],
            [ 'id' => '3411', 'name' => 'El Hamadia', 'ar_name' => 'الحمادية', 'slug' => 'el-hamadia', 'wilaya_id' => 34 ],
            [ 'id' => '3413', 'name' => 'Medjana', 'ar_name' => 'مجانة', 'slug' => 'medjana', 'wilaya_id' => 34 ],
            [ 'id' => '3415', 'name' => 'Djaafra', 'ar_name' => 'جعافرة', 'slug' => 'djaafra', 'wilaya_id' => 34 ],
            [ 'id' => '3431', 'name' => 'Bir Kasdali', 'ar_name' => 'بئر قاصد علي', 'slug' => 'bir-kasdali', 'wilaya_id' => 34 ],
            [ 'id' => '3501', 'name' => 'Boumerdes', 'ar_name' => 'بومرداس', 'slug' => 'boumerdes', 'wilaya_id' => 35 ],
            [ 'id' => '3502', 'name' => 'Boudouaou', 'ar_name' => 'بودواو', 'slug' => 'boudouaou', 'wilaya_id' => 35 ],
            [ 'id' => '3504', 'name' => 'Bordj Menaiel', 'ar_name' => 'برج منايل', 'slug' => 'bordj-mnaiel', 'wilaya_id' => 35 ],
            [ 'id' => '3505', 'name' => 'Baghlia', 'ar_name' => 'بغلية', 'slug' => 'baghlia', 'wilaya_id' => 35 ],
            [ 'id' => '3507', 'name' => 'Naciria', 'ar_name' => 'الناصرية', 'slug' => 'naciria', 'wilaya_id' => 35 ],
            [ 'id' => '3509', 'name' => 'Isser', 'ar_name' => 'يسر', 'slug' => 'isser', 'wilaya_id' => 35 ],
            [ 'id' => '3514', 'name' => 'Thenia', 'ar_name' => 'الثنية', 'slug' => 'thenia', 'wilaya_id' => 35 ],
            [ 'id' => '3523', 'name' => 'Dellys', 'ar_name' => 'دلس', 'slug' => 'dellys', 'wilaya_id' => 35 ],
            [ 'id' => '3531', 'name' => 'Khemis El Khechna', 'ar_name' => 'خميس الخشنة', 'slug' => 'khemis-el-khechna', 'wilaya_id' => 35 ],
            [ 'id' => '3601', 'name' => 'El Tarf', 'ar_name' => 'الطارف', 'slug' => 'el-tarf', 'wilaya_id' => 36 ],
            [ 'id' => '3602', 'name' => 'Bouhadjar', 'ar_name' => 'بوحجار', 'slug' => 'bouhadjar', 'wilaya_id' => 36 ],
            [ 'id' => '3603', 'name' => "Ben M'hidi", 'ar_name' => 'بن مهيدي', 'slug' => 'ben-mhidi', 'wilaya_id' => 36 ],
            [ 'id' => '3605', 'name' => 'El Kala', 'ar_name' => 'القالة', 'slug' => 'el-kala', 'wilaya_id' => 36 ],
            [ 'id' => '3608', 'name' => 'Bouteldja', 'ar_name' => 'بوثلجة', 'slug' => 'bouteldja', 'wilaya_id' => 36 ],
            [ 'id' => '3613', 'name' => 'Drean', 'ar_name' => 'الذرعان', 'slug' => 'drean', 'wilaya_id' => 36 ],
            [ 'id' => '3616', 'name' => 'Besbes', 'ar_name' => 'البسباس', 'slug' => 'besbes', 'wilaya_id' => 36 ],
            [ 'id' => '3701', 'name' => 'Tindouf', 'ar_name' => 'تندوف', 'slug' => 'tindouf', 'wilaya_id' => 37 ],
            [ 'id' => '3801', 'name' => 'Tissemsilt', 'ar_name' => 'تيسمسيلت', 'slug' => 'tissemsilt', 'wilaya_id' => 38 ],
            [ 'id' => '3802', 'name' => 'Bordj Bounaama', 'ar_name' => 'برج بونعامة', 'slug' => 'bordj-bounaama', 'wilaya_id' => 38 ],
            [ 'id' => '3803', 'name' => 'Theniet El Had', 'ar_name' => 'ثنية الاحد', 'slug' => 'theniet-el-had', 'wilaya_id' => 38 ],
            [ 'id' => '3804', 'name' => 'Lazharia', 'ar_name' => 'الأزهرية', 'slug' => 'lazharia', 'wilaya_id' => 38 ],
            [ 'id' => '3806', 'name' => 'Lardjem', 'ar_name' => 'لرجام', 'slug' => 'lardjem', 'wilaya_id' => 38 ],
            [ 'id' => '3809', 'name' => 'Bordj Emir Abdelkader', 'ar_name' => 'برج الأمير عبد القادر', 'slug' => 'bordj-emir-abdelkader', 'wilaya_id' => 38 ],
            [ 'id' => '3811', 'name' => 'Khemisti', 'ar_name' => 'خميستي', 'slug' => 'khemisti', 'wilaya_id' => 38 ],
            [ 'id' => '3813', 'name' => 'Ammari', 'ar_name' => 'عماري', 'slug' => 'ammari', 'wilaya_id' => 38 ],
            [ 'id' => '3901', 'name' => 'El Oued', 'ar_name' => 'الوادي', 'slug' => 'el-oued', 'wilaya_id' => 39 ],
            [ 'id' => '3902', 'name' => 'Robbah', 'ar_name' => 'الرباح', 'slug' => 'robbah', 'wilaya_id' => 39 ],
            [ 'id' => '3904', 'name' => 'Bayadha', 'ar_name' => 'البياضة', 'slug' => 'bayadha', 'wilaya_id' => 39 ],
            [ 'id' => '3906', 'name' => 'Guemar', 'ar_name' => 'قمار', 'slug' => 'guemar', 'wilaya_id' => 39 ],
            [ 'id' => '3908', 'name' => 'Reguiba', 'ar_name' => 'الرقيبة', 'slug' => 'reguiba', 'wilaya_id' => 39 ],
            [ 'id' => '3911', 'name' => 'Debila', 'ar_name' => 'الدبيلة', 'slug' => 'debila', 'wilaya_id' => 39 ],
            [ 'id' => '3913', 'name' => 'Hassi Khalifa', 'ar_name' => 'حاسي خليفة', 'slug' => 'hassi-khalifa', 'wilaya_id' => 39 ],
            [ 'id' => '3914', 'name' => 'Taleb Larbi', 'ar_name' => 'الطالب العربي', 'slug' => 'taleb-larbi', 'wilaya_id' => 39 ],
            [ 'id' => '3918', 'name' => 'Magrane', 'ar_name' => 'المقرن', 'slug' => 'magrane', 'wilaya_id' => 39 ],
            [ 'id' => '3926', 'name' => 'Mih Ouensa', 'ar_name' => 'اميه وانسة', 'slug' => 'mih-ouensa', 'wilaya_id' => 39 ],
            [ 'id' => '4001', 'name' => 'Khenchela', 'ar_name' => 'خنشلة', 'slug' => 'khenchela', 'wilaya_id' => 40 ],
            [ 'id' => '4003', 'name' => 'Kais', 'ar_name' => 'قايس', 'slug' => 'kais', 'wilaya_id' => 40 ],
            [ 'id' => '4005', 'name' => 'El Hamma', 'ar_name' => 'الحامة', 'slug' => 'el-hamma', 'wilaya_id' => 40 ],
            [ 'id' => '4006', 'name' => 'Ain Touila', 'ar_name' => 'عين الطويلة', 'slug' => 'ain-touila', 'wilaya_id' => 40 ],
            [ 'id' => '4008', 'name' => 'Bouhmama', 'ar_name' => 'بوحمامة', 'slug' => 'bouchmama', 'wilaya_id' => 40 ],
            [ 'id' => '4011', 'name' => 'Chechar', 'ar_name' => 'ششار', 'slug' => 'chechar', 'wilaya_id' => 40 ],
            [ 'id' => '4013', 'name' => 'Babar', 'ar_name' => 'بابار', 'slug' => 'babar', 'wilaya_id' => 40 ],
            [ 'id' => '4016', 'name' => 'Ouled Rechache', 'ar_name' => 'أولاد رشاش', 'slug' => 'ouled-rechache', 'wilaya_id' => 40 ],
            [ 'id' => '4101', 'name' => 'Souk Ahras', 'ar_name' => 'سوق أهراس', 'slug' => 'souk-ahras', 'wilaya_id' => 41 ],
            [ 'id' => '4102', 'name' => 'Sedrata', 'ar_name' => 'سدراتة', 'slug' => 'sedrata', 'wilaya_id' => 41 ],
            [ 'id' => '4104', 'name' => 'Mechroha', 'ar_name' => 'المشروحة', 'slug' => 'mechroha', 'wilaya_id' => 41 ],
            [ 'id' => '4105', 'name' => 'Ouled Driss', 'ar_name' => 'أولاد إدريس', 'slug' => 'ouled-driss', 'wilaya_id' => 41 ],
            [ 'id' => '4108', 'name' => 'Taoura', 'ar_name' => 'تاورة', 'slug' => 'taoura', 'wilaya_id' => 41 ],
            [ 'id' => '4110', 'name' => 'Haddada', 'ar_name' => 'الحدادة', 'slug' => 'haddada', 'wilaya_id' => 41 ],
            [ 'id' => '4112', 'name' => 'Merahna', 'ar_name' => 'المراهنة', 'slug' => 'merahna', 'wilaya_id' => 41 ],
            [ 'id' => '4114', 'name' => 'Bir Bouhouche', 'ar_name' => 'بئر بوحوش', 'slug' => 'bir-bouhouche', 'wilaya_id' => 41 ],
            [ 'id' => '4115', 'name' => "M'daourouche", 'ar_name' => 'مداوروش', 'slug' => 'mdaourouche', 'wilaya_id' => 41 ],
            [ 'id' => '4116', 'name' => 'Oum El Adhaim', 'ar_name' => 'أم العظايم', 'slug' => 'oum-el-adhaim', 'wilaya_id' => 41 ],
            [ 'id' => '4201', 'name' => 'Tipaza', 'ar_name' => 'تيبازة', 'slug' => 'tipaza', 'wilaya_id' => 42 ],
            [ 'id' => '4208', 'name' => 'Hadjout', 'ar_name' => 'حجوط', 'slug' => 'hadjout', 'wilaya_id' => 42 ],
            [ 'id' => '4209', 'name' => 'Sidi Amar', 'ar_name' => 'سيدي أعمر', 'slug' => 'sidi-amar', 'wilaya_id' => 42 ],
            [ 'id' => '4210', 'name' => 'Gouraya', 'ar_name' => 'قوراية', 'slug' => 'gouraya', 'wilaya_id' => 42 ],
            [ 'id' => '4214', 'name' => 'Cherchell', 'ar_name' => 'شرشال', 'slug' => 'cherchell', 'wilaya_id' => 42 ],
            [ 'id' => '4215', 'name' => 'Damous', 'ar_name' => 'الداموس', 'slug' => 'damous', 'wilaya_id' => 42 ],
            [ 'id' => '4217', 'name' => 'Fouka', 'ar_name' => 'فوكة', 'slug' => 'fouka', 'wilaya_id' => 42 ],
            [ 'id' => '4218', 'name' => 'Bou Ismail', 'ar_name' => 'بواسماعيل', 'slug' => 'bou-ismail', 'wilaya_id' => 42 ],
            [ 'id' => '4219', 'name' => 'Ahmar El Ain', 'ar_name' => 'أحمر العين', 'slug' => 'ahmar-el-ain', 'wilaya_id' => 42 ],
            [ 'id' => '4224', 'name' => 'Kolea', 'ar_name' => 'القليعة', 'slug' => 'kolea', 'wilaya_id' => 42 ],
            [ 'id' => '4301', 'name' => 'Mila', 'ar_name' => 'ميلة', 'slug' => 'mila', 'wilaya_id' => 43 ],
            [ 'id' => '4302', 'name' => 'Ferdjioua', 'ar_name' => 'فرجيوة', 'slug' => 'ferdjioua', 'wilaya_id' => 43 ],
            [ 'id' => '4303', 'name' => 'Chelghoum Laid', 'ar_name' => 'شلغوم العيد', 'slug' => 'chelghoum-laid', 'wilaya_id' => 43 ],
            [ 'id' => '4306', 'name' => 'Teleghma', 'ar_name' => 'التلاغمة', 'slug' => 'teleghma', 'wilaya_id' => 43 ],
            [ 'id' => '4308', 'name' => 'Tadjenanet', 'ar_name' => 'تاجنانت', 'slug' => 'tadjenanet', 'wilaya_id' => 43 ],
            [ 'id' => '4310', 'name' => 'Oued Endja', 'ar_name' => 'وادي النجاء', 'slug' => 'oued-endja', 'wilaya_id' => 43 ],
            [ 'id' => '4314', 'name' => 'Bouhatem', 'ar_name' => 'بوحاتم', 'slug' => 'bouhatem', 'wilaya_id' => 43 ],
            [ 'id' => '4315', 'name' => 'Rouached', 'ar_name' => 'الرواشد', 'slug' => 'rouached', 'wilaya_id' => 43 ],
            [ 'id' => '4317', 'name' => 'Grarem Gouga', 'ar_name' => 'القرارم قوقة', 'slug' => 'grarem-gouga', 'wilaya_id' => 43 ],
            [ 'id' => '4318', 'name' => 'Sidi Merouane', 'ar_name' => 'سيدي مروان', 'slug' => 'sidi-merouane', 'wilaya_id' => 43 ],
            [ 'id' => '4319', 'name' => 'Tassadane Haddada', 'ar_name' => 'تسدان حدادة', 'slug' => 'tassadane-haddada', 'wilaya_id' => 43 ],
            [ 'id' => '4323', 'name' => 'Terrai Bainen', 'ar_name' => 'ترعي باينان', 'slug' => 'terrai-bainen', 'wilaya_id' => 43 ],
            [ 'id' => '4330', 'name' => 'Ain Beida Harriche', 'ar_name' => 'عين البيضاء أحريش', 'slug' => 'ain-beida-harriche', 'wilaya_id' => 43 ],
            [ 'id' => '4401', 'name' => 'Ain Defla', 'ar_name' => 'عين الدفلى', 'slug' => 'ain-defla', 'wilaya_id' => 44 ],
            [ 'id' => '4402', 'name' => 'Miliana', 'ar_name' => 'مليانة', 'slug' => 'miliana', 'wilaya_id' => 44 ],
            [ 'id' => '4403', 'name' => 'Boumedfaa', 'ar_name' => 'بومدفع', 'slug' => 'boumedfaa', 'wilaya_id' => 44 ],
            [ 'id' => '4404', 'name' => 'Khemis', 'ar_name' => 'خميس', 'slug' => 'khemis', 'wilaya_id' => 44 ],
            [ 'id' => '4405', 'name' => 'Hammam Righa', 'ar_name' => 'حمام ريغة', 'slug' => 'hammam-righa', 'wilaya_id' => 44 ],
            [ 'id' => '4407', 'name' => 'Djelida', 'ar_name' => 'جليدة', 'slug' => 'djelida', 'wilaya_id' => 44 ],
            [ 'id' => '4408', 'name' => 'El Amra', 'ar_name' => 'العامرة', 'slug' => 'el-amra', 'wilaya_id' => 44 ],
            [ 'id' => '4410', 'name' => 'El Attaf', 'ar_name' => 'العطاف', 'slug' => 'el-attaf', 'wilaya_id' => 44 ],
            [ 'id' => '4411', 'name' => 'El Abadia', 'ar_name' => 'العبادية', 'slug' => 'el-abadia', 'wilaya_id' => 44 ],
            [ 'id' => '4412', 'name' => 'Djendel', 'ar_name' => 'جندل', 'slug' => 'djendel', 'wilaya_id' => 44 ],
            [ 'id' => '4414', 'name' => 'Ain Lechiakh', 'ar_name' => 'عين الاشياخ', 'slug' => 'ain-lechiakh', 'wilaya_id' => 44 ],
            [ 'id' => '4416', 'name' => 'Rouina', 'ar_name' => 'الروينة', 'slug' => 'rouina', 'wilaya_id' => 44 ],
            [ 'id' => '4422', 'name' => 'Bordj El Emir Khaled', 'ar_name' => 'برج الأمير خالد', 'slug' => 'bordj-el-emir-khaled', 'wilaya_id' => 44 ],
            [ 'id' => '4431', 'name' => 'Bathia', 'ar_name' => 'بطحية', 'slug' => 'bathia', 'wilaya_id' => 44 ],
            [ 'id' => '4501', 'name' => 'Naama', 'ar_name' => 'النعامة', 'slug' => 'naama', 'wilaya_id' => 45 ],
            [ 'id' => '4502', 'name' => 'Mecheria', 'ar_name' => 'المشرية', 'slug' => 'mecheria', 'wilaya_id' => 45 ],
            [ 'id' => '4503', 'name' => 'Ain Sefra', 'ar_name' => 'عين الصفراء', 'slug' => 'ain-sefra', 'wilaya_id' => 45 ],
            [ 'id' => '4505', 'name' => 'Sfissifa', 'ar_name' => 'سفيسيفة', 'slug' => 'sfissifa', 'wilaya_id' => 45 ],
            [ 'id' => '4506', 'name' => 'Moghrar', 'ar_name' => 'مغرار', 'slug' => 'moghrar', 'wilaya_id' => 45 ],
            [ 'id' => '4507', 'name' => 'Asla', 'ar_name' => 'عسلة', 'slug' => 'asla', 'wilaya_id' => 45 ],
            [ 'id' => '4510', 'name' => 'Mekmen Ben Amar', 'ar_name' => 'مكمن بن عمار', 'slug' => 'mekmen-ben-amar', 'wilaya_id' => 45 ],
            [ 'id' => '4601', 'name' => 'Ain Temouchent', 'ar_name' => 'عين تموشنت', 'slug' => 'ain-temouchent', 'wilaya_id' => 46 ],
            [ 'id' => '4604', 'name' => 'Hammam Bou Hadjar', 'ar_name' => 'حمام بوحجر', 'slug' => 'hammam-bou-hadjar', 'wilaya_id' => 46 ],
            [ 'id' => '4609', 'name' => 'Ain Larbaa', 'ar_name' => 'عين الأربعاء', 'slug' => 'ain-larbaa', 'wilaya_id' => 46 ],
            [ 'id' => '4614', 'name' => 'El Maleh', 'ar_name' => 'المالح', 'slug' => 'el-maleh', 'wilaya_id' => 46 ],
            [ 'id' => '4619', 'name' => 'El Amria', 'ar_name' => 'العامرية', 'slug' => 'el-amria', 'wilaya_id' => 46 ],
            [ 'id' => '4622', 'name' => 'Ain Kihel', 'ar_name' => 'عين الكيحل', 'slug' => 'ain-kihel', 'wilaya_id' => 46 ],
            [ 'id' => '4623', 'name' => 'Beni Saf', 'ar_name' => 'بني صاف', 'slug' => 'beni-saf', 'wilaya_id' => 46 ],
            [ 'id' => '4625', 'name' => 'Oulhassa Gheraba', 'ar_name' => 'ولهاصة الغرابة', 'slug' => 'oulhassa-gheraba', 'wilaya_id' => 46 ],
            [ 'id' => '4701', 'name' => 'Ghardaia', 'ar_name' => 'غرداية', 'slug' => 'ghardaia', 'wilaya_id' => 47 ],
            [ 'id' => '4703', 'name' => 'Dhayet Ben Dhahoua', 'ar_name' => 'ضاية بن ضحوة', 'slug' => 'dhayet-ben-dhahoua', 'wilaya_id' => 47 ],
            [ 'id' => '4704', 'name' => 'Berriane', 'ar_name' => 'بريان', 'slug' => 'berriane', 'wilaya_id' => 47 ],
            [ 'id' => '4705', 'name' => 'Metlili', 'ar_name' => 'متليلي', 'slug' => 'metlili', 'wilaya_id' => 47 ],
            [ 'id' => '4706', 'name' => 'El Guerrara', 'ar_name' => 'القرارة', 'slug' => 'el-geurrara', 'wilaya_id' => 47 ],
            [ 'id' => '4708', 'name' => 'Zelfana', 'ar_name' => 'زلفانة', 'slug' => 'zelfana', 'wilaya_id' => 47 ],
            [ 'id' => '4710', 'name' => 'Bounoura', 'ar_name' => 'بونورة', 'slug' => 'bounoura', 'wilaya_id' => 47 ],
            [ 'id' => '4713', 'name' => 'Mansoura', 'ar_name' => 'المنصورة', 'slug' => 'mansoura-ghardaia', 'wilaya_id' => 47 ],
            [ 'id' => '4801', 'name' => 'Relizane', 'ar_name' => 'غليزان', 'slug' => 'relizane', 'wilaya_id' => 48 ],
            [ 'id' => '4802', 'name' => 'Oued Rhiou', 'ar_name' => 'وادي رهيو', 'slug' => 'oued-rhiou', 'wilaya_id' => 48 ],
            [ 'id' => '4807', 'name' => "El H'madna", 'ar_name' => 'الحمادنة', 'slug' => 'el-hmadna', 'wilaya_id' => 48 ],
            [ 'id' => '4808', 'name' => "Sidi M'hamed Ben Ali", 'ar_name' => 'سيدي أمحمد بن علي', 'slug' => 'sidi-mhamed-ben-ali', 'wilaya_id' => 48 ],
            [ 'id' => '4811', 'name' => 'Ammi Moussa', 'ar_name' => 'عمي موسى', 'slug' => 'ammi-moussa', 'wilaya_id' => 48 ],
            [ 'id' => '4812', 'name' => 'Zemmoura', 'ar_name' => 'زمورة', 'slug' => 'zemmoura', 'wilaya_id' => 48 ],
            [ 'id' => '4814', 'name' => 'Djidiouia', 'ar_name' => 'جديوية', 'slug' => 'djidiouia', 'wilaya_id' => 48 ],
            [ 'id' => '4817', 'name' => 'El Matmar', 'ar_name' => 'المطمر', 'slug' => 'el-matmar', 'wilaya_id' => 48 ],
            [ 'id' => '4819', 'name' => 'Ain Tarek', 'ar_name' => 'عين طارق', 'slug' => 'ain-tarek', 'wilaya_id' => 48 ],
            [ 'id' => '4822', 'name' => 'Mazouna', 'ar_name' => 'مازونة', 'slug' => 'mazouna', 'wilaya_id' => 48 ],
            [ 'id' => '4825', 'name' => 'Yellel', 'ar_name' => 'يلل', 'slug' => 'tellel', 'wilaya_id' => 48 ],
            [ 'id' => '4827', 'name' => 'Ramka', 'ar_name' => 'الرمكة', 'slug' => 'ramka', 'wilaya_id' => 48 ],
            [ 'id' => '4828', 'name' => 'Mendes', 'ar_name' => 'منداس', 'slug' => 'mendes', 'wilaya_id' => 48 ],
            [ 'id' => '103', 'name' => 'Charouine', 'ar_name' => 'شروين', 'slug' => 'charouine', 'wilaya_id' => 49 ],
            [ 'id' => '109', 'name' => 'Timimoun', 'ar_name' => 'تيميمون', 'slug' => 'timimoun', 'wilaya_id' => 49 ],
            [ 'id' => '116', 'name' => 'Tinerkouk', 'ar_name' => 'تنركوك', 'slug' => 'tinerkouk', 'wilaya_id' => 49 ],
            [ 'id' => '123', 'name' => 'Aougrout', 'ar_name' => 'أوقروت', 'slug' => 'aougrout', 'wilaya_id' => 49 ],
            [ 'id' => '125', 'name' => 'Bordj Badji Mokhtar', 'ar_name' => 'برج باجي مختار', 'slug' => 'bordj-badji-mokhtar', 'wilaya_id' => 50 ],
            [ 'id' => '705', 'name' => 'Ouled Djellal', 'ar_name' => 'أولاد جلال', 'slug' => 'ouled-djellal', 'wilaya_id' => 51 ],
            [ 'id' => '708', 'name' => 'Sidi Khaled', 'ar_name' => 'سيدي  خالد', 'slug' => 'sidi-khaled', 'wilaya_id' => 51 ],
            [ 'id' => '803', 'name' => 'Ouled Khodeir', 'ar_name' => 'أولاد خضير', 'slug' => 'ouled-khodeir', 'wilaya_id' => 52 ],
            [ 'id' => '807', 'name' => 'Beni Abbes', 'ar_name' => 'بني عباس', 'slug' => 'beni-abbes', 'wilaya_id' => 52 ],
            [ 'id' => '811', 'name' => 'Igli', 'ar_name' => 'إقلي', 'slug' => 'igli', 'wilaya_id' => 52 ],
            [ 'id' => '814', 'name' => 'El Ouata', 'ar_name' => 'الواتة', 'slug' => 'el-ouata', 'wilaya_id' => 52 ],
            [ 'id' => '818', 'name' => 'Kerzaz', 'ar_name' => 'كرزاز', 'slug' => 'kerzaz', 'wilaya_id' => 52 ],
            [ 'id' => '1103', 'name' => 'In Ghar', 'ar_name' => 'إينغر', 'slug' => 'in-ghar', 'wilaya_id' => 53 ],
            [ 'id' => '1108', 'name' => 'In Salah', 'ar_name' => 'عين صالح', 'slug' => 'in-salah', 'wilaya_id' => 53 ],
            [ 'id' => '1104', 'name' => 'In Guezzam', 'ar_name' => 'عين قزام', 'slug' => 'in-guezzam', 'wilaya_id' => 54 ],
            [ 'id' => '1107', 'name' => 'Tin Zouatine', 'ar_name' => 'تين زواتين', 'slug' => 'tin-zouatine', 'wilaya_id' => 54 ],
            [ 'id' => '3013', 'name' => 'Touggourt', 'ar_name' => 'تقرت', 'slug' => 'touggourt', 'wilaya_id' => 55 ],
            [ 'id' => '3014', 'name' => 'El-Hadjira', 'ar_name' => 'الحجيرة', 'slug' => 'el-hadjira', 'wilaya_id' => 55 ],
            [ 'id' => '3015', 'name' => 'Taibet', 'ar_name' => 'الطيبات', 'slug' => 'taibet', 'wilaya_id' => 55 ],
            [ 'id' => '3016', 'name' => 'Temacine', 'ar_name' => 'تماسين', 'slug' => 'temacine', 'wilaya_id' => 55 ],
            [ 'id' => '3019', 'name' => 'Megarine', 'ar_name' => 'المقارين', 'slug' => 'megarine', 'wilaya_id' => 55 ],
            [ 'id' => '3302', 'name' => 'Djanet', 'ar_name' => 'جانت', 'slug' => 'djanet', 'wilaya_id' => 56 ],
            [ 'id' => '3927', 'name' => 'El Meghaier', 'ar_name' => 'المغير', 'slug' => 'el-meghaier', 'wilaya_id' => 57 ],
            [ 'id' => '3928', 'name' => 'Djamaa', 'ar_name' => 'جامعة', 'slug' => 'djamaa', 'wilaya_id' => 57 ],
            [ 'id' => '4702', 'name' => 'El Menia', 'ar_name' => 'المنيعة', 'slug' => 'el-menia', 'wilaya_id' => 58 ],
        ];

        /*
         * Add Daira Items
         *
         */
        foreach ($Dairaitems as $Dairaitem) {
            $newDairaitem = Daira::where('slug', '=', $Dairaitem['slug'])->first();
            if ($newDairaitem === null) {
                $newDairaitem = Daira::create([
                    'name'          => $Dairaitem['name'],
                    'ar_name'          => $Dairaitem['ar_name'],
                    'slug'          => $Dairaitem['slug'],
                    'id'          => $Dairaitem['id'],
                    'wilaya_id'          => $Dairaitem['wilaya_id'],
                ]);
            }
        }
    }
}
